### PR TITLE
first commit lesson-4-2

### PR DESCRIPTION
**Pull request by raul-2001**

### CODE REVIEW

**Comment by Jkuffler** [comment]
You have two separate Connect sections. One is placed below the footer. Reformat your index.html to match what's expected for the assignment. Before you do - make sure to see how it looks in the browser and try to catch those things as you proceed 👍 
I'm recommending to go ahead and make the hyperlinks you've created in index.html be clickable in the browser as well. If you would like some extra guidance you can reach out to the Slack general discussion or use your preferred search engine for assistance.

**Comment by raul-2001** [comment]
Thanks for your review my code. I have checked all my mistakes. I am gonna solve all of those.

**Comment by raul-2001** [comment]
I have solved all mistakes.

**Comment by Jkuffler** [comment]
nice work with the improvements. Regarding email links: look into using the `mailto` attribute for anchor tags 👍 

The remaining code below can be deleted from the bottom of your `index.html` - lines 74-74
```
    "https://github.com/raul-2001/"
    "https://www.linkedin.com/in/raul-guliyev-3a3670110"
    rlqv2001@gmail.com
```

javscript file is off to a nice start

**Comment by raul-2001** [comment]
Thanks for your reviewing my code Mr Jason! I have removed the email link as you pointed in line 74-74. You can see the changing code in the next pull request of lesson-4-3.

**Pull request merged**
